### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by mathbunnyru**
Some small code fixes. I will be more than happy if you'll recompile Decibel when you'll be able to do that. Thank you for such a wonderful application.

### CODE REVIEW

**Comment by sbooth** [comment]
Thank you for submitting this PR.

Nice catches on the problems in `DSFDecoder` and `SetAPETagFromMetadata()`.  I'm definitely interested in merging those changes.

I'm less inclined to merge the  changes that are stylistic in nature such as the use of prefix `++` instead of postfix, initializer list variable order, etc. since they don't fix any problems.

**Comment by mathbunnyru** [comment]
@sbooth you can just cherry-pick commits you want 👍 I tried to do every change in its own commit.

I made stylistic changes to make the code able with -Wall -Wextra -Werror -pedantic -Wold-style-cast -Wconversion -Wsign-conversion -Wunreachable-code, which really improve code quality. I would really appreciate if you merge these changes too, but, that's up to you, of course. These changes make code a little bit faster, slightly cleaner and more analysable by static code analyzers. Btw, I used cppcheck to make some of this changes and merging all commits will make its output much more readable.

Thank you once again for your work.

**Comment by sbooth** [comment]
Thanks for the additional information. I grabbed cppcheck and understand better where some of those changes came from.  I also got a bunch of warnings about 1-argument constructors not being marked as explicit, so that's probably a good change to make as well.

What tool recommended the changes made in 2157aee?

It might make sense to add `-Wall -Wextra` to the project's `Other Warning Flags`.  `-pedantic` is probably too much for me as I'm not really interested in being warned about Clang extensions.

**Comment by mathbunnyru** [comment]
That tool is just me:) Preincrements are just faster and I saw an opportunity to fix postincrements in those cases. I was afraid to make changes like adding explicit and static keywords, because I don't know the code as well as you do.

**Comment by sbooth** [comment]
I think preincrement vs. postincrement speed is an interesting discussion.  I'm under the impression that they're the same for simple types since the compiler is generating the code, but for custom `operator++` implementations there *may* be a difference.

http://stackoverflow.com/questions/24901/is-there-a-performance-difference-between-i-and-i-in-c

**Comment by mathbunnyru** [comment]
@sbooth just don't accept that commit, if you don't want to, I'm absolutely ok with that. For me, when I see postincrements, that makes me think - why did author used them here? And to eliminate such thoughts, and make the code more elegant (in my opinion), I always prefer preincrement when possible.

**Comment by sbooth** [comment]
I'll work on merging the commits later today.  Thanks!

**Comment by sbooth** [comment]
I cherry-picked the relevant commits and they've been pushed to master.  I think I messed up the conflict merge for `OggSpeexDecoder.cpp` but I'll fix it.  Thanks again.

**Comment by mathbunnyru** [comment]
You're welcome. Hope one day you'll update Decibel with some new features. Thank you for such great apps.

**Pull request closed without merging**
