### PR TITLE
Fix loopable region

### PR DESCRIPTION
**Pull request by mixage**
Running this code did not ... repeat the region:

```
NSError *error= nil;
NSURL *url = [NSURL fileURLWithPath:FILE_PATH];
_player = [[SFBAudioPlayer alloc]init];
SFBLoopableRegionDecoder *decoder = [[SFBLoopableRegionDecoder alloc]initWithURL:url framePosition:START_FRAME frameLength:NUM_FRAMES repeatCount:REPEATCOUNT error:&error];
[_player enqueueDecoder:decoder forImmediatePlayback:YES error:&error];
[_player playReturningError:&error];
```

### CODE REVIEW

**Comment by sbooth** [comment]
There is definitely a missing `repeatCount` in https://github.com/sbooth/SFBAudioEngine/blob/c94313a66d13b24cd3c254628d51294af6ae5b83/Decoders/SFBLoopableRegionDecoder.m#L57 

It makes me wonder whether `GCC_WARN_UNUSED_PARAMETER` should be enabled.

I'm not sure if the other changes in this PR are required, though.

**Comment by sbooth** [comment]
I think PR #255 contains all the necessary changes.

**Comment by sbooth** [comment]
If you'd like to revert the other changes I'm happy to merge this PR.

**Comment by mixage** [comment]
I'm not sure to know the right way to do this... Should I push a new commit?

**Comment by sbooth** [comment]
> I'm not sure to know the right way to do this... Should I push a new commit?

Yes, you can just push additional commits and they'll be squashed into one when merged.

**Comment by sbooth** [comment]
Once the changes in `MainMenu.xib` are reverted this should be ready to go.

**Comment by mixage** [comment]
Done. (Xcode made these changes just by viewing the .xib)

NB: loop does'nt work after reverting SFBLoopableRegionDecoder.m row 183 to:

`if ( _repeatCount && _frameLength == (_framesDecoded / _frameLength))
`

Any idea? Thanks :)

**Comment by mixage** [comment]
The region plays once, regardless of the value of REPEAT_COUNT

```
NSError *error= nil;
NSURL *url = [NSURL fileURLWithPath:FILE_PATH];
_player = [[SFBAudioPlayer alloc]init];
SFBLoopableRegionDecoder *decoder = [[SFBLoopableRegionDecoder alloc]initWithURL:url framePosition:START_FRAME frameLength:NUM_FRAMES repeatCount:REPEAT_COUNT error:&error];
[_player enqueueDecoder:decoder forImmediatePlayback:YES error:&error];
[_player playReturningError:&error];
```

**Comment by sbooth** [comment]
I will take a closer look at this later today when I have a bit more time.

**Comment by sbooth** [comment]
Could you verify whether the proposed fix in #255 corrects the problem for you?

**Comment by mixage** [comment]
Works like a charm :)
Thank you!

**Pull request closed without merging**
