### PR TITLE
Simplify piece of code

### PR DESCRIPTION
**Pull request by mathbunnyru**
Just found common part of three branches.
Also, there seems to be a bug in this code, because two branches are equal.

I found it using cppcheck tool, by the way. I think you will find it helpful.

### CODE REVIEW

**Comment by sbooth** [comment]
This looks reasonable, thanks.

I don't think there is a bug in the code; I structured it that way to make the fallback case clearer.  Ideally the `relativeVolume->identification()` shouldn't be empty but I don't think the spec requires it.

**Comment by mathbunnyru** [comment]
@sbooth I was talking about this line. It's the same in the 2nd and 3rd cases.

```AddFloatToDictionary(dictionary, Metadata::kAlbumGainKey, volumeAdjustment);
```

**Comment by mathbunnyru** [comment]
By description given it must be
```
Metadata::kTrackGainKey
```
in the 3rd vase.

**Comment by sbooth** [comment]
Ah, I see.  The code and comment should definitely match.  So it probably makes sense to use `Metadata::kTrackGainKey` for the fallback case.

**Comment by mathbunnyru** [comment]
@sbooth fixed.
Please, also take a look at this commit.

**Pull request merged**
